### ISSUE TITLE
Update Readme.md file

### ISSUE THREAD

**Issue by codemaniac-sahil** [codemaniac-sahil/currency_converter_react#1]
Update the Readme.md file for this project.

**Comment by Chitvan14** [comment]
Hi @codemaniac-sahil, I can add a nice readme file for this repo, please assign this issue to me.

**Comment by codemaniac-sahil** [comment]
okay @Chitvan14, you are good to go.

**Comment by codemaniac-sahil** [comment]
You did very well @Chitvan14
