### ISSUE TITLE
Add a github icon at the corner to link to this repo

### ISSUE THREAD

**Issue by dipanshusingh2107** [codemaniac-sahil/currency_converter_react#12]
Can I add a github image at the corner that links the site to this github repo.
I have attached a sample below 

![68747470733a2f2f692e696d6775722e636f6d2f373033694c69532e706e67](https://user-images.githubusercontent.com/47363596/193463239-f870055e-1008-42da-bd85-6fa7e1f401e1.png)

**Comment by codemaniac-sahil** [comment]
That will be awesome @dipanshusingh2107

**Comment by codemaniac-sahil** [comment]
@dipanshusingh2107 you are good to go

**Comment by codemaniac-sahil** [comment]
@dipanshusingh2107 you did great
