### ISSUE TITLE
The minimum money value should not be negative

### ISSUE THREAD

**Issue by subhashis2204** [codemaniac-sahil/currency_converter_react#13]
Currently the application accepts negative input which is ambiguous as money could not be negative. I would like to fix this bug.

**Comment by codemaniac-sahil** [comment]
Okay @subhashis2204

**Comment by codemaniac-sahil** [comment]
You are good to go

**Comment by codemaniac-sahil** [comment]
@subhashis2204 are you still working on this issue?
