### ISSUE TITLE
The amount is not formatted correctly 

### ISSUE THREAD

**Issue by subhashis2204** [codemaniac-sahil/currency_converter_react#14]
# Objective
The converted amount should be rounded off to 2 decimal places for better understanding.

**Comment by subhashis2204** [comment]
@AwsYaseen22 I was working on this issue. You should have reported it before working on it.

**Comment by AwsYaseen22** [comment]
Sorry @subhashis2204 I didn’t realize that; it was my first contribution and that is a good lesson to take; sorry again.

**Comment by Nishith-Savla** [comment]
Hi @codemaniac-sahil, there is still a minute improvement that can be done in this. The code merged doesn't work for values like `1.005` and gives `1` instead of `1.01`.

Assign this to me, so I can fix this by adding Epsilon to the original number.

**Comment by codemaniac-sahil** [comment]
Yeah, I find this bug as well. @Nishith-Savla, you are good to go.
