### ISSUE TITLE
Convert styling to TailwindCSS

### ISSUE THREAD

**Issue by rajdip-b** [codemaniac-sahil/currency_converter_react#18]
I want to refactor the entire project styling to TailwindCSS and also add basic animations. Can i be assigned this issue under Hacktoberfest2022?

**Comment by codemaniac-sahil** [comment]
Yes you can @rajdip-b

**Comment by rajdip-b** [comment]
@codemaniac-sahil i have some color codes for a nice dark theme. do i apply it?

**Comment by codemaniac-sahil** [comment]
Yes @rajdip-b

**Comment by codemaniac-sahil** [comment]
feel free to do anything you want

**Comment by codemaniac-sahil** [comment]
would you please change font-family

**Comment by codemaniac-sahil** [comment]
https://github.com/codemaniac-sahil/currency_converter_react/issues/11#issuecomment-1264698355
like this

**Comment by rajdip-b** [comment]
Yeah, sure!

**Comment by codemaniac-sahil** [comment]
apart from that everything is awesome.

**Comment by rajdip-b** [comment]
@codemaniac-sahil I can't seem to figure out the font name. Meanwhile, mind checking out (this)[https://fonts.google.com/specimen/K2D?query=k2d&preview.text=k2d&preview.text_type=custom] font and see if this works for you?

**Comment by codemaniac-sahil** [comment]
It is good

**Comment by rajdip-b** [comment]
@codemaniac-sahil i have updated the font
