### ISSUE TITLE
Add Docker support

### ISSUE THREAD

**Issue by cmjchrisjones** [codemaniac-sahil/currency_converter_react#22]
The ability to run the project inside a docker container so that Node/NPM isn't required as a pre-requisite, and you have an isolated development environment. The only pre-requisite that would be required would be Docker.

[blog](https://auth0.com/blog/use-docker-to-create-a-node-development-environment/) with more information about the benefits of using Docker

**Comment by cmjchrisjones** [comment]
Fixed by #21

**Comment by codemaniac-sahil** [comment]
@cmjchrisjones you have done great
