### ISSUE TITLE
Use a better (free) exchange rates API as the current one has only 150k requests per month

### ISSUE THREAD

**Issue by Nishith-Savla** [codemaniac-sahil/currency_converter_react#26]
The current exchange rates API only offers 150k requests per month but there is one API: [exchangerate.host](https://exchangerate.host/) which doesn't have any such limit.

So I would suggest that migrating to this API would be beneficial as the project becomes popular.

I would be happy to work on this.

**Comment by codemaniac-sahil** [comment]
Yes please do this as soon as possible

**Comment by Nishith-Savla** [comment]
Sure :+1:

**Comment by codemaniac-sahil** [comment]
actually it is happening because in api request there is undefined variable and i am fixing it

**Comment by Nishith-Savla** [comment]
Ohhk

**Comment by Nishith-Savla** [comment]
You do that for now. I'll understand the current API response first and then replace it with the new API https://exchangerate.host

**Comment by codemaniac-sahil** [comment]
yes please

**Comment by codemaniac-sahil** [comment]
please do this

**Comment by codemaniac-sahil** [comment]
you are good to go @Nishith-Savla

**Comment by codemaniac-sahil** [comment]
@Nishith-Savla are you working on this?

**Comment by Nishith-Savla** [comment]
Yes, it will submit a PR today itself
