### ISSUE TITLE
Text inside dropdown menu is not visible

### ISSUE THREAD

**Issue by codemaniac-sahil** [codemaniac-sahil/currency_converter_react#27]
Text inside dropdown menu is not visible 
![Screenshot (31)](https://user-images.githubusercontent.com/58036566/193543614-8b7831f2-96e0-45d2-8a98-e1f9ab4f1b7c.png)

**Comment by satyamrs00** [comment]
I am working on this .
Assign it to me

**Comment by codemaniac-sahil** [comment]
okay @satyamrs00

**Comment by codemaniac-sahil** [comment]
@satyamrs00 you did great.
