### ISSUE TITLE
Adding an Open Source license 

### ISSUE THREAD

**Issue by dipanshusingh2107** [codemaniac-sahil/currency_converter_react#33]
@codemaniac-sahil Please add License.md file

**Comment by codemaniac-sahil** [comment]
@dipanshusingh2107 you are good to go

**Comment by dipanshusingh2107** [comment]
I can't give the License. @codemaniac-sahil  you have to add it yourself by creating a LICENSE.md file [https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository](url)

**Comment by codemaniac-sahil** [comment]
okay @dipanshusingh2107
