### ISSUE TITLE
Design UI/UX

### ISSUE THREAD

**Issue by codemaniac-sahil** [codemaniac-sahil/currency_converter_react#5]
Design project's UI/UX. It should be attractive.

**Comment by Zaynabnadada** [comment]
Hi, I'll love to work on this project
mind if i ask, can it be any project concerned with UI/U?

**Comment by codemaniac-sahil** [comment]
@Zaynabnadada, you are good to go.

**Comment by MAYURIKOTHARI19** [comment]
Can you assign this to me I would love to work on it..

**Comment by codemaniac-sahil** [comment]
@MAYURIKOTHARI19 You can work on this issue.

**Comment by MAYURIKOTHARI19** [comment]
@codemaniac-sahil  can you please brief what I have to do and from where should I start ? I need to design a figma file? I am newbee this is my first open source project.

**Comment by codemaniac-sahil** [comment]
@MAYURIKOTHARI19 okay, you just need to create figma file.
If you have any doubts connect with me on discord. 
Discord id codemaniac_sahil#3664
